#!/bin/zsh

#############
# 2 Aliases #
#############

# Configuration
alias resource='source ~/.zshrc'
alias  editzsh='kate -s zsh'

# File manipulation
alias   grep='grep --color=auto'
alias    svn='colorsvn'
alias     cp='cp --interactive'
alias     mv='mv --interactive'
alias     rm='rm --interactive'
alias     gi="grep -i --color=always"
alias     gv="grep -v"
alias rccopy="rsync --partial --progress --append --rsh=ssh -r -h "
alias rcmove="rsync --partial --progress --append --rsh=ssh -r -h --remove-sent-files"

# File system display
alias  ls='ls --classify --tabsize=0 --literal --color=auto --show-control-chars --human-readable --group-directories-first'
alias  ll='ls -l'
alias  la='ls --almost-all'
alias  lla='ls -la'
alias  lsd='ls --directory */'
alias    c='clear'
alias less='less --quiet'
alias    s='cd ..'

# File system sizes
alias  df='df --human-readable'
alias  du='du --human-readable'
alias duh="du -h | sort -h"
alias  md='mkdir'
alias  rd='rmdir'

# Global shortcuts
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
alias -g .......='../../../../../..'
alias -g ........='../../../../../../..'
alias -g .........='../../../../../../../..'

# Man pages
alias man='man -P /usr/bin/most'

# Root stuff
alias boss='sudo -s'

# Package managment
alias   search='apt-cache search'
alias     show='apt-cache show'
alias   loadry='sudo apt-get install'
alias  expload='apt-get -t experimental install'
alias     nuke='sudo apt-get remove'
alias  upgrade='sudo apt-get upgrade'
alias  dist-up='sudo apt-get dist-upgrade'
alias   update='sudo apt-get -o Acquire::http::Pipeline-Depth=0 update'
alias    files='apt-file show'
alias upgraydd='update && upgrade'
alias   autorm='sudo apt-get autoremove'
alias  implode='sudo apt-get remove --purge'
alias   addppa='sudo add-apt-repoisitory'
alias  killppa='sudo ppa-purge'
alias  sources='sudo vim /etc/apt/sources.list'
alias   policy='apt-cache policy'

# Utilities
alias turnoff='sudo shutdown -h now'
alias   alarm='/usr/bin/beep -f 300; /usr/bin/beep -f 400; /usr/bin/beep -f 500; /usr/bin/beep -f 600'

# Media
alias film='mplayer -vo vdpau'
alias open='xdg-open'