#!/bin/zsh

__motd() {
    HOSTNAME=$(uname -n)
    KERNEL=$(uname -r)
    CPU=$(uname -p)
    ARCH="$(lsb_release -sd | cut -c 8-) $(uname -m)"
    UPTIME=$(</proc/uptime)
    UPTIME=${UPTIME%%.*}

    UPTIME="$(( UPTIME/60/60/24 )) days, $(( UPTIME/60/60%24 )) hours, $(( UPTIME/60%60 )) minutes, $(( UPTIME%60 )) seconds"
    PACKAGES=$(dpkg --list | wc -l)
    SHELLNAME=$(echo $SHELL | cut -d '/' -f 3)
    USEDMEM=$(free -m | grep Mem | sed -r "s/Mem:\s+([0-9]+)\s+([0-9]+).*/${red__}\2M${blue__} \/ \1M/")
    USEDSWAP=$(free -m | grep Swap | sed -r "s/Swap:\s+([0-9]+)\s+([0-9]+).*/${green__}\2M${blue__} \/ \1M/")
    FREEDISK=$(df -Tlh -x tmpfs -x devtmpfs --total | grep total | sed -r "s/total\s+\-\s+([0-9.]+\w)\s+([0-9.]+\w).*/${yellow__}\2 ${blue__}\/ \1/")


echo -e "${cyan__}         _sudZUZ#Z#XZo=_         "
echo -e "${cyan__}      _jmZZ2!!~---~!!X##wa      ${blue_}//=========================---${____}"
echo -e "${cyan__}   .<wdP~~            -!YZL,     ${blue_}\\ ${cyan_}User:${blue__}     $USER${____}"
echo -e "${cyan__}  .mX2\'       _%aaa__     XZ[.   ${blue_}\\ ${cyan_}Hostname:${blue__} $HOSTNAME${____}"
echo -e "${cyan__}  oZ[      _jdXY!~?S#wa   ]Xb;     ${blue_}\\ ${cyan_}Kernel:${blue__}   $KERNEL${____}"
echo -e "${cyan__} _#e\'     .]X2(     ~Xw|  )XXc     ${blue_}\\ ${cyan_}Os:${blue__}       Debian Linux $ARCH${____}"
echo -e "${cyan__}.2Z       ]X[.       xY|  ]oZ(       ${blue_}\\ ${cyan_}Uptime:${blue__}   $UPTIME${____}"
echo -e "${cyan__}.2#;      )3k;     _s\!~   jXf\`       ${blue_}\\ ${cyan_}Shell:${blue__}    $SHELLNAME${____}"
echo -e "${cyan__} 1Z#      -]Xb/    ~    __#2(          ${blue_}\\ ${cyan_}Terminal:${blue__} $TERM${____}"
echo -e "${cyan__} -Zo;       +\!4ZwaaaauZZXY'            ${blue_}\\ ${cyan_}Cpu:${blue__}      $CPU${____}"
echo -e "${cyan__}  *#[,        ~-?!!!!!!-~                ${blue_}\\ ${cyan_}Mem:${blue__}      $USEDMEM${____}      "
echo -e "${cyan__}   XUb;.                                  ${blue_}\\ ${cyan_}Swap:${blue__}     $USEDSWAP${____}"
echo -e "${cyan__}    )YXL,,                                 ${blue_}\\ ${cyan_}Disk:${blue__}     $FREEDISK${____}"
echo -e "${cyan__}      +3#bc,                                ${blue_}\\ ${cyan_}Packages:${blue__}     $PACKAGES${____}"
echo -e "${cyan__}        -)SSL,,                              ${blue_}\\=========================---${____}"
echo -e "${cyan__}           ~~~~~                 "
}

